import type { Torrent } from './interfaces/index.mjs'

const defaultProperties: (keyof Torrent)[] = [
  'hash',
  'queue',
  'name',
  'total_size',
  'state',
  'progress',
  'num_seeds',
  'total_seeds',
  'num_peers',
  'total_peers',
  'download_payload_rate',
  'upload_payload_rate',
  'eta',
  'ratio',
  'distributed_copies',
  'is_auto_managed',
  'time_added',
  'tracker_host',
  'save_path',
  'total_done',
  'total_uploaded',
  'max_download_speed',
  'max_upload_speed',
  'seeds_peers_ratio',
  'file_priorities',
  'add_paused',
  'compact_allocation',
  'download_location',
  'max_connections',
  'max_upload_slots',
  'prioritize_first_last_pieces',
  'move_completed',
  'move_completed_path',
  'pre_allocate_storage',
  'sequential_download',
  'seed_mode',
  'super_seeding',
]

export default defaultProperties
